force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Car Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Opel</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Client_Cars__c/Client_Cars__c.object-meta.xml
<CustomObject>
    <label>Client Car(s)</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Client Cars Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Cars__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Client Cars</relationshipLabel>
    <relationshipName>Client_Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Cars__c/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <label>Car Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passenger</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Bus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Order__c/Client_Order__c.object-meta.xml
<CustomObject>
    <label>Client Order</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Client Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Order__c/fields/Total_Order_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Order_Price__c</fullName>
    <label>Total Order Price</label>
    <summarizedField>Part_Order__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Part_Order__c.Client_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Part_Order__c/Part_Order__c.object-meta.xml
<CustomObject>
    <label>Part Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Part Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parts Order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Order__c/fields/Client_Order__c.field-meta.xml
<CustomField>
    <fullName>Client_Order__c</fullName>
    <label>Client Order</label>
    <referenceTo>Client_Order__c</referenceTo>
    <relationshipLabel>Parts Order</relationshipLabel>
    <relationshipName>Parts_Order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Part_Order__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Parts_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/L_StoreService.cls
public with sharing class L_StoreService {

    public static String currentSObjectAPIName;

    public static Contact[] getClientsWithCarsAndOrders() {
        return [
            SELECT Id, Name,
            (SELECT Id, Car__r.Brand__c, Car_Type__c, Car__r.Model__c FROM Client_Cars__r),
            (SELECT Id, Name, Order_Description__c, Total_Order_Price__c FROM Client_Order__r)
            FROM Contact
            LIMIT 1000
        ];
    }

    public static Contact[] getClientWithCarsAndOrders(Id clientId) {
        return [
            SELECT Id, Name,
            (SELECT Id, Car__r.Brand__c, Car_Type__c, Car__r.Model__c FROM Client_Cars__r),
            (SELECT Id, Name, Order_Description__c, Total_Order_Price__c FROM Client_Order__r)
            FROM Contact
            WHERE Id = :clientId
        ];
    }

    public static L_StoreHelper.WrapClient[] createWrapClients(Contact[] clients) {
        L_StoreHelper.WrapClient[] wrapClients = new L_StoreHelper.WrapClient[]{};

        for (Contact client : clients) {
            L_StoreHelper.WrapClient wrapClient = new L_StoreHelper.WrapClient(
                client.Id, 
                client.Name,
                createWrapCars(client.Client_Cars__r),
                createWrapClientOrders(client.Client_Order__r)
            );

            wrapClients.add(wrapClient);
        }

        return wrapClients;
    }

    public static Part_Order__c[] getPartOrdersByClientOrderId(Id clientOrderId) {
        return [
            SELECT Id, Name, Client_Order__r.Name, Part__r.Name
            FROM Part_Order__c
            WHERE Client_Order__c = :clientOrderId
        ];
    }

    private static L_StoreHelper.WrapCar[] createWrapCars(Client_Cars__c[] clientCars) {
        L_StoreHelper.WrapCar[] cars = new L_StoreHelper.WrapCar[]{};

        for (Client_Cars__c clientCar : clientCars) {

            cars.add(new L_StoreHelper.WrapCar(
                clientCar.Id,
                clientCar.Car__r.Brand__c,
                clientCar.Car__r.Model__c,
                clientCar.Car_Type__c
            ));
        }

        return cars;
    }

    private static L_StoreHelper.WrapClientOrder[] createWrapClientOrders(Client_Order__c[] clientOrders) {
        L_StoreHelper.WrapClientOrder[] orders = new L_StoreHelper.WrapClientOrder[]{};

        for (Client_Order__c clientOrder : clientOrders) {

            orders.add(new L_StoreHelper.WrapClientOrder(
                clientOrder.Id,
                clientOrder.Name,
                clientOrder.Order_Description__c,
                clientOrder.Total_Order_Price__c
            ));
        }

        return orders;
    }

    private static String getSObjectAPINameById(Id sObjectId) {
        String sObjectAPIName;

        if (sObjectId != null) {
            sObjectAPIName = String.valueOf(sObjectId.getSobjectType());
        }

        return sObjectAPIName;
    }
}